In [1]:
import numpy as np

In [2]:
a = np.array([3,2,1,4])

In [3]:
a

array([3, 2, 1, 4])

In [4]:
a = np.array([3,2,1,4], np.int32)  #for memory management

In [5]:
a

array([3, 2, 1, 4], dtype=int32)

In [6]:
a[1]

2

In [7]:
b = np.array([[2,3,4]])

In [8]:
b[0,1]

3

In [9]:
b.shape

(1, 3)

In [10]:
b.dtype

dtype('int64')

In [11]:
b[0,1] = 5

In [12]:
b

array([[2, 5, 4]])